steps:
  # Python 3.9 빌드 환경 사용
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Building Python application..."
        python --version
        pip install -r requirements.txt
        python main.py
